# Generated by Django 4.1.6 on 2023-02-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('STOCK_MANAGER', 'STOCK_MANAGER'), ('ONLINE_SALE_MANAGER', 'ONLINE_SALE_MANAGER')], max_length=255),
        ),
    ]
