# Generated by Django 4.1.6 on 2023-02-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('base_curve', models.CharField(default='8.6mm', max_length=255)),
                ('diameter', models.CharField(max_length=255)),
                ('power', models.CharField(default='0.00', max_length=255)),
                ('material', models.CharField(default='HEMA', max_length=255)),
                ('water_content', models.CharField(default='38%', max_length=255)),
                ('package', models.CharField(default='2 lenses + 1 case', max_length=500)),
                ('eTag', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
