# Generated by Django 4.1.6 on 2023-03-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockvariation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
