# Generated by Django 4.1.6 on 2023-02-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='base_curve',
            field=models.FloatField(default=8.6, max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='diameter',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='power',
            field=models.FloatField(default=0.0, max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='water_content',
            field=models.FloatField(default=38, max_length=255),
        ),
    ]
