# Generated by Django 4.1.6 on 2023-02-05 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_base_curve_alter_category_diameter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('n_tone', models.IntegerField()),
                ('cycle_period', models.CharField(choices=[('MONTHLY', 'MONTHLY'), ('QUATERLY', 'QUATERLY'), ('HALF-YEARLY', 'HALF-YEARLY'), ('YEARLY', 'YEARLY')], default='YEARLY', max_length=20)),
                ('eTag', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
    ]
