# Generated by Django 4.1.6 on 2023-02-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='cycle_period',
            field=models.CharField(choices=[('MONTHLY', 'MONTHLY'), ('QUARTERLY', 'QUARTERLY'), ('HALF-YEARLY', 'HALF-YEARLY'), ('YEARLY', 'YEARLY')], default='YEARLY', max_length=20),
        ),
    ]
