# Generated by Django 4.1.6 on 2023-02-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_subcategory_cycle_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='cycle_period',
            field=models.CharField(max_length=255),
        ),
    ]
