# Generated by Django 4.1.6 on 2023-02-06 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PLUS', 'PLUS'), ('MINUS', 'MINUS')], default='MINUS', max_length=20)),
                ('quantity', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('eTag', models.CharField(max_length=255)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
